language: objective-c

install:
  - brew install neko haxe
  - cd ..
  - mkdir haxelib
  - haxelib setup haxelib
before_script:
  - cd $TRAVIS_BUILD_DIR
  - haxelib install munit
  - haxelib dev haxe-websocket-server .
script:
  - haxe test.hxml
  - haxelib run munit test